// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNoti struct {
	Userid      string `json:"userid"`
	Name        string `json:"name"`
	Related     string `json:"related"`
	Type        string `json:"type"`
	Doctor      string `json:"doctor"`
	Appointment string `json:"appointment"`
}

type NotiSchema struct {
	Name        string `json:"name"`
	Related     string `json:"related"`
	Type        string `json:"type"`
	Doctor      string `json:"doctor"`
	Appointment string `json:"appointment"`
}

type ReturnNoti struct {
	Notilist []*NotiSchema `json:"notilist"`
}

type UserWhoCall struct {
	Userid string `json:"userid"`
}
